### ISSUE TITLE
Make the URL check optional

### ISSUE THREAD

**Issue by ocefpaf** [ioos/erddapy#114]
Bob brought this to my attention via e-mail. While those who use `erddapy` as a URL constructor may need that, those who use it as a data-access library are fine waiting for the failure until the data is requested.

**Comment by abkfenris** [comment]
You can partially blame me for this.

We're using erddapy for data access to cache some NDBC data from Coastwatch. With the ERDDAP subscription system, when Bob cranked up the refresh rate, our refreshes increased just as much.

Maybe add a keyword argument (`skip_head=False`?) to `get_download_url` that is called by default by the `to_` methods? 

https://github.com/ioos/erddapy/blob/2bd1e866a6543d5eaa88c587fadce1cf8c5cdf72/erddapy/erddapy.py#L285-L345

Probably should also expose it through the `to_` methods for anyone who wants to keep the old method.

**Comment by ocefpaf** [comment]
That makes sense. I'll try to address this ASAP. Thanks!

**Comment by abkfenris** [comment]
I can take a swing at it if you want.

**Comment by ocefpaf** [comment]
> I can take a swing at it if you want.

I have a staged changed that will change the `to_xarray`, let me see if I can push that today. After that I'm planning on turning off the `check_url`, which doesn't fetch the header per se but I believe is the mechanism responsible for what you all are experiencing.

PS: I do want PRs from you and that will come at a price, like the keys to the repo and your name as a maintainer :insert-evil-laugh:

**Comment by ocefpaf** [comment]
I removed the checks in #116. They will be useful only when I implement the `fsspec` for `to_xarray`.

**Comment by abkfenris** [comment]
Oooh boy. I gotta read up on `fsspec` sometime if you're threatening me with keys to the kingdom.
