### ISSUE TITLE
Re-include `requests_kwargs` to control connections to ERDDAP server

### ISSUE THREAD

**Issue by abkfenris** [ioos/erddapy#131]
Before a13ee24d1922a52abc35c91a085041d1afc51b7e `ERDDAP.requests_kwargs` is a dict that can be set for any keyword arguments to be passed to `requests.get()` when retrieving data. It is still [documented](https://github.com/ioos/erddapy/blob/d410244a0c50f8339a146ee147c9d56fd8e7ef68/erddapy/erddapy.py#L59) as an attribute.

Now attempting to set `ERDDAP.requests_kwargs` [throws an `AttributeError`](https://github.com/gulfofmaine/buoy_barn/pull/190/checks?check_run_id=940192781#step:7:142).

For example this allows setting a `timeout` argument that causes requests to throw a [`requests.Timeout`](https://2.python-requests.org/en/master/api/#requests.Timeout) if it is taking too long to retrieve information (without using something like signals to do the same).

**Comment by ocefpaf** [comment]
Definitely a regression bug. I wanted to have a more consistent way to pass requests args around and ended up removing them :-(
