### ISSUE TITLE
erddapy with griddap .to_xarray() .to_netcdf() response forces .ncCF (not a griddap option)

### ISSUE THREAD

**Issue by shaunwbell** [ioos/erddapy#134]
I know griddap isn't officially supported but it previously had worked for the purposes I needed... seems the implementation of .ncCF response may be throwing it off (url building it forces .ncCF as the response type now but there isn't a .ncCF type for griddap)

if I change the url to response nc - i get what I expect as returned data

gist of a simple example showing the failure in trying to load - https://gist.github.com/shaunwbell/b11e4ae63638010866b6ae9d64261004

and my adhoc solution (which is purpose built, not holistic or i would push a pull request)
```python
    
  def to_xarray(self, **kw):
        """Load the data request into a xarray.Dataset.

        Accepts any `xr.open_dataset` keyword arguments.
        """
        import xarray as xr

        url = self.get_download_url(response="nc")
        nc = _nc_dataset(url, auth=self.auth, **self.requests_kwargs)
        return xr.open_dataset(xr.backends.NetCDF4DataStore(nc), **kw)
```

am i missing a part of the API to set this explicitly or is it hardcoded into the script?

thanks

erddapy = 0.7.0
python 3.8.5

**Comment by ocefpaf** [comment]
> I know griddap isn't officially supported but it previously had worked for the purposes I needed... seems the implementation of .ncCF response may be throwing it off (url building it forces .ncCF as the response type now but there isn't a .ncCF type for griddap)

Indeed `griddap` is not supported it but this is a bug nonetheless. Thanks for opening the issue!

> am i missing a part of the API to set this explicitly or is it hardcoded into the script?

It is hardcoded, and that was a poor choice of design. `xarray` can handle any netCDF-like response so the right fix is to pass a response kw arg to `to_xarray`, keeping `ncCF` as default though. Do you want to send a PR?

**Comment by ocefpaf** [comment]
Actually it looks like `ncCF` is not supported in `griddap`, so the best course of actions is to check the protocol and define the default. PR soon...

**Comment by shaunwbell** [comment]
That should do it... gist looks like as I would expect it!  Thanks for the rapid response.

This seems like a modification I could have tackled myself too... next time :) - it'll be good practice

**Comment by ocefpaf** [comment]
> This seems like a modification I could have tackled myself too... next time :) - it'll be good practice

Indeed. The only reason I sent the PR is b/c I was embarrassed to have it hard-coded like that in the first place :-)
