### ISSUE TITLE
HTTP Error with erddap V2.10

### ISSUE THREAD

**Issue by shaunwbell** [ioos/erddapy#154]
seems a little something has changed and is throwing an error - I've not looked into the erddapy code but here is what I did (both on the swfsc erddap server and my own):

```
from erddapy import ERDDAP
import pandas as pd

e = ERDDAP(server="https://coastwatch.pfeg.noaa.gov/erddap")

print(url)

url = e.get_search_url(search_for="whoi", response="csv")

df = pd.read_csv(url)
print(
    f'We have {len(set(df["tabledap"].dropna()))} '
    f'tabledap, {len(set(df["griddap"].dropna()))} '
    f'griddap, and {len(set(df["wms"].dropna()))} wms endpoints.'
)
```

Throws a http 500 error and following  the generated link gives the following explicit error:

```
Error {
    code=500;
    message="Internal Server Error: ERROR in parseISODateTime: for first character of dateTime='(ANY)' isn't a digit!";
}
```

**Comment by ocefpaf** [comment]
I can confirm that. It looks like the default placeholder `"(ANY)"` is no longer accepted in the date field. Should be an easy fix, hold on...
