### ISSUE TITLE
Allow server-side functions within time parameter

### ISSUE THREAD

**Issue by thogar-computer** [ioos/erddapy#161]
Afternoon, 
currently if a user wants to call an URL like the following from erddapy;

http://erddap.sensors.ioos.us/erddap/tabledap/uk_gov_metoffice_62103.htmlTable?time,latitude,longitude,wind_speed,wind_from_direction&time=max(time)+0minutes

It will fail on [line 50 - erddapy.py](https://github.com/ioos/erddapy/blob/master/erddapy/erddapy.py#L50)

``` python
parse_date_time = parse_time_string(date_time)[0]
```

Even though this can be done from within pandas, these types of server-side functions greatly reduce the amount of data transmitted.  

As a starter, having a check on the value to see if it starts with max/min? I am not totally sure on the full list of functions...

If agreed, i am happy to pick this up :)

**Comment by ocefpaf** [comment]
That would be a nice addition. If you want to send a PR it will be most welcomed!

**Comment by thogar-computer** [comment]
cheers for the merge :) i will close this now
