### ISSUE TITLE
Created the API for url search in griddap

### ISSUE THREAD

**Issue by avishmehta68710** [ioos/erddapy#175]
Hi @ocefpaf  
I tried to create an API for url_search in griddap. Can you please have a look and suggest the changes. please refer to #176 

Thanks

**Comment by avishmehta68710** [comment]
Sir as per requested by you i have made the changes 
sir i have made a pr #178

**Comment by avishmehta68710** [comment]
Hi @ocefpaf 
I have submitted the google summer of code proposal. can you please give me feedback.

**Comment by avishmehta68710** [comment]
Hi @ocefpaf 
it would be great if u can spare some time and check my proposal and give feedback
thanks

**Comment by ocefpaf** [comment]
Implement during GSoC.
