### ISSUE TITLE
Get the attributes of a dataset

### ISSUE THREAD

**Issue by rbardaji** [ioos/erddapy#180]
Hello erddapy developers,

Is it possible to get the attributes of a dataset in a list or dictionary or JSON?

In the examples, I only find information on how to get the attributes with the 'get_info_url' method and then display it on screen with an iframe. I would need the attributes information in a variable.

Thanks!

**Comment by ocefpaf** [comment]
You can make a request for any other response, json included, however we are planning on adding a Dataset-like class to help with that. Here is a prototype: https://nbviewer.jupyter.org/gist/ocefpaf/ae0d650af68c0670e5f09d35c887129c

**Comment by ocefpaf** [comment]
Even without the implementation above one can request the JSON response. Closing this but please reopen if that is not what you needed.
