### ISSUE TITLE
get_search_url with empty time bounds forms an inappropriate URL

### ISSUE THREAD

**Issue by nicholas512** [ioos/erddapy#181]
## Expected behaviour:
I can make an advanced dataset search without supplying time bounds

## Actual behaviour
If time bounds are not provided to `get_search_url`, erddapy generates the URI string  `&minTime=(ANY)&maxTime=(ANY)` which returns an error from the server.

## Reproduceable example

```python
from erddapy import ERDDAP
import pandas as pd

e = ERDDAP(server="https://gliders.ioos.us/erddap")

kw = {
    "standard_name": "sea_water_temperature",
    "min_lon": -72.0,
    "max_lon": -69.0,
    "min_lat": 38.0,
    "max_lat": 41.0,
    "cdm_data_type": "trajectoryprofile"
}

search_url = e.get_search_url(response="html", **kw)
pd.read_csv(search_url)
```

## Suggested fix
If time bounds are empty, instead of generating `&minTime=(ANY)&maxTime=(ANY)` erddapy should generate `&minTime=&maxTime=`

## Versions
erddapy == 1.0.0
python == 3.6.10

**Comment by ocefpaf** [comment]
I wonder when that stopped working, `(ANY)` was the default :-(

Fixing this... Thanks for the report!

**Comment by ocefpaf** [comment]
Ah! It still works. The problem there is that you are using the `HTML` response a `CSV` reader. Try to change the to:

```python
search_url = e.get_search_url(response="csv", **kw)
pd.read_csv(search_url)
```

**Comment by nicholas512** [comment]
oops. You're right. Silly mistake, I'll close the issue.

**Comment by ocefpaf** [comment]
> oops. You're right. Silly mistake

Been there, done that ;-p

> I'll close the issue.

Thanks!
