### ISSUE TITLE
Multiple ERDDAP search

### ISSUE THREAD

**Issue by ocefpaf** [ioos/erddapy#190]
We could do an async search on a pre-determined list or maybe wrap an interface for [1].

@callumrollo is that something you would like to tackle?

[1] https://coastwatch.pfeg.noaa.gov/erddap/download/SearchMultipleERDDAPs.html

**Comment by ocefpaf** [comment]
Here is a hacky example on how to do that: https://nbviewer.jupyter.org/gist/ocefpaf/74f91d9aa9c4fa726bfba171b3edcadf

**Comment by callumrollo** [comment]
I tried integrating the extra checks into `erddapy.url_handling._urlopen`, but multiprocessing did not like the lru cache and kwargs, caused problems with the pickling. I think the least bad aproach would be a new function multi_urlopen for this specific purpose. I'll create a minimum working example
