### ISSUE TITLE
Constraining a dataset when an erddap variable name starts with "time" but it isn't a time

### ISSUE THREAD

**Issue by shaunwbell** [ioos/erddapy#198]
So I use the CF DSG datatypes (point, profile, timeseries, trajectory) as my dataset id identifiers with my erddap datasets (which i then point to and set as my cf_role) - these variables are usually populated with string names.  

For example: i concatenate multiple instruments on a fixed mooring within a single erddap dataset, each instrument gets a timeseries_id  that is fixed for the instrument... say mymooring_myinstrument_morerelevantdetails.  And if I wanted to retrieve all data from just a single instrument I can constrain on that value... 

See example of description in screen shot:
<img width="1049" alt="Screen Shot 2021-07-16 at 1 23 19 PM" src="https://user-images.githubusercontent.com/6493489/126004746-d913cb91-966c-4588-99b9-213834ae0c22.png">

However and herein is my problem... 
erddapy looks for any constraint to start with 'time' and then assumes the content is a datetime object, but there could be cases where this is not truly the case

the issue is the following code for reference
```
    385             for k, v in _constraints.items():
    386                 if k.startswith("time"):
    387                     _constraints.update({k: parse_dates(v)})
    388             _constraints = _quote_string_constraints(_constraints)
    389             _constraints_url = _format_constraints_url(_constraints)
```

clearly the simple answer is for me to rename my variable id to not start with time... but this may just obscure an issue that another user may have should the word "time" reference data that is not easily translated into a datetime object.

**Comment by ocefpaf** [comment]
> clearly the simple answer is for me to rename my variable id to not start with time... but this may just obscure an issue that another user may have should the word "time" reference data that is not easily translated into a datetime object.

We should handle this better in `erddapy`. I'll look into this ASAP. Thanks for the report!

**Comment by MathewBiddle** [comment]
I'm wondering if it should be looking for the variable with standard_name = time ?

Or drop the startswith and look for exactly time, as that is a special variable in ERDDAP.

**Comment by ocefpaf** [comment]
> Or drop the startswith and look for exactly time, as that is a special variable in ERDDAP.

Probably the latter. I don't recall why I used the `startswith` to start with, no pun intended, maybe there was a corner case. Anyway, if there is one, I need to write tests for it first.

**Comment by shaunwbell** [comment]
@ocefpaf 
> Edit: can you send a URL for that server/dataset so I can play with it a little?

Unfortunately, its only available on an internal facing server - I could make a subset to be hosted on an external server?, but I don't have an external server that I manage or have admin rights on

**Comment by ocefpaf** [comment]
> Unfortunately, its only available on an internal facing server - I could make a subset to be hosted on an external server?, but I don't have an external server that I manage or have admin rights on

No problem. I'll let you know when we address this so you can test it out.
