### ISSUE TITLE
Conda vs pip last versions are different

### ISSUE THREAD

**Issue by gmaze** [ioos/erddapy#223]
Hi,
It seems that erddapy is available under [1.2 with conda](https://anaconda.org/conda-forge/erddapy) but only with [1.1 with pip](https://pypi.org/simple/erddapy/).
This trigger some inconsistencies in dependencies check under different CI systems ([eg here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=401982&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) which fails [argopy feedstock](https://github.com/conda-forge/argopy-feedstock/pull/7))
Is this done on purpose ?
thanks
g

**Comment by ocefpaf** [comment]
Sorry, but since my laptop and cellphone got stolen I've been waiting on:

https://github.com/pypa/pypi-support/issues/1201

If you can comment there maybe it would help get this unstuck. For now, new versions on conda only.

PS: would a GitHub release that is pip installable help?

**Comment by gmaze** [comment]
Apparently pypa/pypi-support#1201 get closed a few hours ago, may be you'll get back to normal soon, this can wait

**Comment by ocefpaf** [comment]
> Apparently [pypa/pypi-support#1201](https://github.com/pypa/pypi-support/issues/1201) get closed a few hours ago, may be you'll get back to normal soon, this can wait Thanks !

I'm pushing it to PyPI ASAP. I guess they saw this issue and decided to fix. It happened literally 10 min after you posted it :smile:

**Comment by ocefpaf** [comment]
Done! See https://pypi.org/project/erddapy/#files

**Comment by gmaze** [comment]
awesome, thanks @ocefpaf !
