### ISSUE TITLE
errdapy not available for Apple Silicon macOS 12 systems 

### ISSUE THREAD

**Issue by truedichotomy** [ioos/erddapy#227]
Currently I'm unable to install errdapy for my Apple Silicon based Mac. Please add support for these systems.

**Comment by abkfenris** [comment]
How are you trying to install it, and what kind of error does it give you? 

It might be easiest for us to help debug if you include the full error log.

**Comment by truedichotomy** [comment]
I get the following error when trying to install using pip:

```
(base) gong@polaris ~ % pip install errdapy
ERROR: Could not find a version that satisfies the requirement errdapy (from versions: none)
ERROR: No matching distribution found for errdapy
(base) gong@polaris ~ % 
```

I wasn't able to install `errdapy` using conda last night but somehow this morning it lets me install. However when I tried to load it in python, I countered the following error:

```
(base) gong@polaris covid19 % ipython
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from erddapy import ERRDAP
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <module>
----> 1 from erddapy import ERRDAP

ImportError: cannot import name 'ERRDAP' from 'erddapy' (/Users/gong/miniforge3/lib/python3.9/site-packages/erddapy/__init__.py)
```

Here is my system info:
```
(base) gong@polaris ~ % uname -a 
Darwin polaris.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```

**Comment by ebridger** [comment]
You have a typo.  `errddapy` has one r, not two. Try: `erddapy`.  
https://pypi.org/search/?q=erddapy&o=

**Comment by truedichotomy** [comment]
Wow, I didn't realize how much my brain had trouble with differentiating ERRDAP and ERDDAP!  Thank you.

**Comment by ocefpaf** [comment]
BTW, erddapy is pure Python, it should run in any system where Python runs.

**Comment by abkfenris** [comment]
My first thought was that it might be trying to pull in a version of Numpy that might be incompatible with Apple Silicon rather than erddapy being the issue itself.
