### ISSUE TITLE
Problem with 00-quick_intro.ipbgy.ipynb 

### ISSUE THREAD

**Issue by slowtoaccept** [ioos/erddapy#242]
I'm a newbie. Installed erddapy as per "pip install erddapy" instructions.
Get a full page of exceptions starting with:
AttributeError                            Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 from erddapy import ERDDAP
      4 e = ERDDAP(
      5     server="UAF",  # NOAA UAF (Unified Access Framework)
      6     protocol="tabledap",
      7     response="csv",
      8 )

File ~\Anaconda3\envs\tide\lib\site-packages\erddapy\__init__.py:3, in <module>
      1 """Easier access to scientific data."""
----> 3 from erddapy.erddapy import ERDDAP
      4 from erddapy.servers import servers
      6 __all__ = ["ERDDAP", "servers"]
.
.
.

Ending in AttributeError: module 'brotli' has no attribute 'error' along with a full page of exceptions.

Are there release requirements? I've always updated Anaconda etc.

**Comment by abkfenris** [comment]
Hmm, it would be helpful to see the full stack trace to tell. Any chance that you can create a Gist with your notebook?

I believe brotli is a requirement of requests, so I'm guessing that a transitive dependency didn't get solved, or that your pip might be mismatched from the conda environment. 

It would be also helpful for us to know the output of a handful of commands:
- `conda env list`
- `which python`
- `which pip`
- `pip debug`
- `python -m pip debug`
- `pip list` (and if the two pip debugs have a different `sys.executable`, then `python -m pip list`)

In the end, uninstalling with pip, and installing with conda is likely to also help take care of the issue the quickest for you. The two package systems tend to manage transitive dependencies differently, and this is the type of situation that conda usually handles better.

**Comment by slowtoaccept** [comment]
@abkfenris Thanks. Re-updated several modules and things now work.
