### ISSUE TITLE
Remove pagination from all responses but HTML in search_for

### ISSUE THREAD

**Issue by ocefpaf** [ioos/erddapy#244]
Items per page does not make sense and can be misleading in non-HTML responses. When someone requests a JSON or CSV they want all the results.

**Comment by ocefpaf** [comment]
@vinisalazar this is probably the last issue you can address before we lay out a plan for the refactor.

**Comment by ocefpaf** [comment]
@vinisalazar if I recall correctly you addressed this one, right? Can we close it?

**Comment by vinisalazar** [comment]
Yep!
