### ISSUE TITLE
Make get_info_url rerun the root info data when no dataset_id is specified.

### ISSUE THREAD

**Issue by ocefpaf** [ioos/erddapy#254]
dataset_id is a mandatory arg but we could make it optional and return the list of all datasets as the root info page.

**Comment by vinisalazar** [comment]
I had a go at this one but running `get_info_url` without `dataset_id` leads to a redirect status (`302`), so the `check_url_response` assert fails on the new test. Should I add more logic to the `get_info_url` function so it returns 200? Or should I write the tests differently for this special case?

Thanks,
Vini

**Comment by vinisalazar** [comment]
For example if I run:
```python
url = e.get_info_url(dataset_id=None)
response = check_url_response(url)

# response has status 302 for redirect
print(response.next_request.url)
```
I get: `https://upwell.pfeg.noaa.gov/erddap/info/index.htmlTable?page=1&itemsPerPage=1000`, that is, when we list all of the datasets, it redirects to an URL containing pagination.

**Comment by ocefpaf** [comment]
> I had a go at this one but running get_info_url without dataset_id leads to a redirect status (302), so the check_url_response assert fails on the new test. Should I add more logic to the get_info_url function so it returns 200? Or should I write the tests differently for this special case?

All you need is to use `check_url_response(url, follow_redirects=True)` for that particular test. We do want it to break when checking, unless the user knows what they are doing and add the redirects.

PS: I was hoping that we would not need to allow redirects with responses other than html/htmlTable but it seems that ERDDAP always uses `?page=1&itemsPerPage=1000` as the default pagination :-(

**Comment by vinisalazar** [comment]
Thanks @ocefpaf, I completely missed the `follow_redirects` arg. That makes sense.
