### ISSUE TITLE
Deprecation warnings for downstream packages

### ISSUE THREAD

**Issue by vinisalazar** [ioos/erddapy#265]
Hi,

The ongoing refactoring project will affect downstream packages such as [gliderpy](https://github.com/ioos/gliderpy) and [argopy](https://github.com/euroargodev/argopy), specially in regards of how they import erddapy modules.

I'm wondering what's the best way to deal with this. My initial plan is to submit PRs to these packages that add `try/except` blocks to erddapy imports, and to create a function in erddapy with a deprecation message.

For example, take the [`fetchers.py` module](https://github.com/ioos/gliderpy/blob/master/gliderpy/fetchers.py) in gliderpy:

```python
from erddapy.url_handling import urlopen
```

This would become:

```python
try:
    from erddapy.url_handling import urlopen
except ImportError:
    from erddapy.core.helpers import deprecation_msg
    deprecation_msg("Some message here, or maybe just the default.")
    from erddapy.core.url import urlopen
```
The `core.helpers` module would be created along with the `deprecation_msg` function, which would be a call of `warnings.warn(message, DeprecationWarning)`. I also consider moving some other objects to this module, such as the `ListLike`, `OptionalStr` types that are used by multiple modules.

Would this be an acceptable approach? Please let me know what you think.

Thank you,
Vini

**Comment by vinisalazar** [comment]
Just realised that it would probably be better to have the `try` block using the new import and falling back to the old one if it doesn't work. In this case, the deprecation warning would need to be implemented in the downstream packages.

**Comment by vinisalazar** [comment]
Also an alternative:

Since some functions are available from the `erddapy.erddapy` module, they could be imported from there:

```python
try:
    from erddapy.erddapy import urlopen
except ImportError:
    print("Please update erddapy.")
    from erddapy.url_handling import urlopen
```

**Comment by ocefpaf** [comment]
We will pin the erddapy in the PRs we send upstream. I don't think we need the try-except block in that case.

**Comment by gmaze** [comment]
hi !
In argopy, we already have a try/except block to handle erddapy versions older than v.0.8:
```python
# Load erddapy according to available version (breaking changes in v0.8.0)
try:
    from erddapy import ERDDAP
    from erddapy.utilities import parse_dates, quote_string_constraints
except:  # noqa: E722
    # >= v0.8.0
    from erddapy.erddapy import ERDDAP
    from erddapy.erddapy import _quote_string_constraints as quote_string_constraints
    from erddapy.erddapy import parse_dates
```
It seems that parse_dates will be in erddapy.core.url in a future release, so what do you recommend ?

**Comment by vinisalazar** [comment]
Hi @gmaze,

Indeed `parse_dates` will be in `erddapy.core.url`, but `erddapy.erddapy` imports objects from that module, so your code snippet should still be valid (for all imports, not just `parse_dates`

Hope this helps.

**Comment by gmaze** [comment]
ok, great, thanks @vinisalazar !

**Comment by ocefpaf** [comment]
Both gliderpy and argopy are well adpated to the latest erddapy. Closing this one.
