### ISSUE TITLE
Impossible to import erddapy with pandas 2.0

### ISSUE THREAD

**Issue by gmaze** [ioos/erddapy#299]
I was building a conda environment with unpinned packages:
  - aiohttp
  - erddapy
  - fsspec
  - netCDF4
  - packaging
  - scipy
  - toolz
  - xarray
  - pandas
  - numpy

When conda/mamba solve this, it peaks the Pandas version 2.0
from which erddapy is trying to import ``parse_time_string`` from ``pandas._libs.tslibs.parsing``
but the ``parse_time_string`` function is not longer available there (apparently it was removed after [v2.0.0.dev0](https://github.com/pandas-dev/pandas/blob/v2.0.0.dev0/pandas/tests/tslibs/test_parsing.py))

following the function signature, it looks to have been replaced by: [parse_datetime_string_with_reso](https://github.com/pandas-dev/pandas/blob/v2.0.0/pandas/_libs/tslibs/parsing.pyi#L14), which was in fact called by ``parse_time_string`` code.

May be erddapy could simply rely on [py_parse_datetime_string](https://github.com/pandas-dev/pandas/blob/v2.0.0/pandas/_libs/tslibs/parsing.pyi#L9) in [here](https://github.com/ioos/erddapy/blob/9779b3f6bd9f8a60a0b271c49dc483b65f69f48b/erddapy/core/url.py#L128) ?

this looks like a recurrent issue for erddapy (#128 #34 #240 )

> At some point we should probably vendor parse_time_string b/c that is not part of pandas' public API.

**Comment by ocefpaf** [comment]
> this looks like a recurrent issue for erddapy (#128 #34 #240 )

Yep. Time to stop the band-aid and fix for good. Working on it...
