### ISSUE TITLE
e.to_xarray falling for new erddapy version

### ISSUE THREAD

**Issue by chiaweh2** [ioos/erddapy#307]
Hi all,

I am developing a jupyternotebook utilizing the erddapy package. My simple code snippet which used to work doesn't seems to work anymore after I reinstall my entire conda environment that run the notebook yesterday. I think it might be related to the erddapy package update.

My code snippet is here 
```
import xarray as xr
from erddapy import ERDDAP

#### access the ERDDAP server
e = ERDDAP(
    server="https://coastwatch.pfeg.noaa.gov/erddap/",    # The URL that the ERDDAP server has
    protocol="griddap",                                   # The data type (griddap or tabledap)
    response="opendap",                                   # different output data type that provided by ERDDAP server       
)

# set the dataset id name 
e.dataset_id = "nceiErsstv4"

# griddap_initialize() help fetch the default variables and constraints available for the data
e.griddap_initialize()

# print available variables and range included in the erddap request
print(e.variables)
print('==========')
print(*e.constraints.items(),sep='\n')

ds = e.to_xarray()
```

The new environment is using the 2.0.1 version. The old working version of erddapy is 1.2.1. After reinstall the erddap to the old version the code above worked as before. Thanks again for creating this useful package!

**Comment by ocefpaf** [comment]
I get a

```
Error {
    code=400;
    message="Bad Request: Query error: fileType=.opendap isn't supported by this dataset.";
}
```

I guess we had a bug in 1.2.1 that used another response. If you change it to `response="nc"` it should work as expected.

**Comment by chiaweh2** [comment]
Thanks for the help!
