### ISSUE TITLE
Fix documentation URL

### ISSUE THREAD

**Issue by ocefpaf** [ioos/erddapy#72]
@mwengren looks like I don't have full rights to the repo b/c I cannot edit the URL in:

![screenshot from 2019-02-21 14-20-28](https://user-images.githubusercontent.com/950575/53188403-06897c80-35e4-11e9-9806-fe7d251a13d0.png)

Can you update that to https://ioos.github.io/erddapy/ please?

**Comment by mwengren** [comment]
Strange.  I guess that must be an admin-level function?  I would expect write privileges would give you access to do that.  I changed it.
