### ISSUE TITLE
Include a link to download the notebooks in the documentation

### ISSUE THREAD

**Issue by choldgraf** [ioos/erddapy#85]
The quick / longer introduction are both quite useful demonstrations of erddapy! It would be helpful to include a link to the notebooks at the top of the example, e.g. something like

"This example is written in a Jupyter Notebook - [click here](https://github.com/ioos/erddapy/blob/master/notebooks/quick_intro.ipynb) to download the notebook so you can run it locally"

(another option would be to use something like [sphinx gallery](https://sphinx-gallery.readthedocs.io/) to generate the examples, but I think that's a longer fix that isn't strictly necessary

**Comment by ocefpaf** [comment]
Done in #90.

**Comment by ocefpaf** [comment]
> (another option would be to use something like [sphinx gallery](https://sphinx-gallery.readthedocs.io/) to generate the examples, but I think that's a longer fix that isn't strictly necessary

Yeah. I'm planning on re-writing the docs and I'll try `sphinx-gallery`. For now let's just add the link.
