### ISSUE TITLE
Call the API page "erddapy API" instead of just "erddapy"

### ISSUE THREAD

**Issue by choldgraf** [ioos/erddapy#86]
I had a hard time figuring out that the documentation page `erddapy` was actually the API page. In the left "contents" menu, I assumed it was a section header rather than a clickable page. I think this would be clearer if it were called "`erddapy` API" here: https://github.com/ioos/erddapy/blob/master/docs/source/erddapy.rst

what do you think?

**Comment by ocefpaf** [comment]
> What do you think?

It is not confusing to me b/c I'm used to project that do not use the wording API for the functions/methods docs. (Old scientist that never learned proper programming don't use the word API.) Adding it does not hurt though. See https://github.com/ioos/erddapy/pull/89.

**Comment by choldgraf** [comment]
I think that works!
