### ISSUE TITLE
query masked by WKT area 

### ISSUE THREAD

**Issue by 7yl4r** [ioos/erddapy#96]
A common task is how to fetch data masked by an arbitrary region of interest (RoI) polygon.
Ideally the OPeNDAP standard & ERDDAP might allow for submission of a WKT, but masking could also be handled on the client side.

@ocefpaf : what are the first steps towards implementing RoI masking in erddapy?

Additional thoughts: 
1. Should efforts to implement RoI queries be focused on the server or is this client workaround worthwhile?
2. Is this feature creep? Perhaps masking is a secondary task which should be kept separate from the core functionality of the API.

**Comment by ocefpaf** [comment]
We need to implement the `griddap` URL parser first. Working on that. Let's keep this one open until then. Once we have that using any object that has a `_geo_interface_` should be possible.

**Comment by MathewBiddle** [comment]
Possibly a server side function in the future.
xref: https://github.com/BobSimons/erddap/issues/55
