### ISSUE TITLE
Support ERDDAP "distinct()" server-side function

### ISSUE THREAD

**Issue by emiliom** [ioos/erddapy#98]
erddapy doesn't currently support ERDDAP "Server-side functions". The only such functions I'm aware of are `distinct()` and various ordering functions. The latter don't really seem necessary in the context of erddapy and pandas, b/c sorting can be done client-side via Pandas. But `distinct()` does make a difference, as it can make the response much smaller, depending on the data.

It's actually very easy to use distinct with erddapy as-is. Once I have the request ready to go, I pass this url to pandas read_csv:
```python
e.get_download_url() + '&distinct()'
```

But figuring out how to do this takes a fair bit of work. It'd save users some effort if this was built into erddapy. I could be persuaded to try to add it myself and submit a PR, but not this month ...

**Comment by ocefpaf** [comment]
Thanks for bring this to my attention. I did not know about that function.

This should be easy to implement, let me try it.

**Comment by ocefpaf** [comment]
For pandas users, like @emiliom mentioned, only `distinct` is necessary. However, `erddapy` can be used as just a URL constructor for apps, etc and then all server-side functions will be valuable. I'll try to implement a "sane" API that we can add any function we need.

**Comment by emiliom** [comment]
Woo-hoo! Thanks!

**Comment by ocefpaf** [comment]
> Woo-hoo! Thanks!

Please let me know if that is working as expected. I'll make a new release soon.

**Comment by emiliom** [comment]
I wont' be able to test it this week; I'm too tied up. But if you remind me early next week, I'm happy to test it.
